spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springhibernatedb
    username: root
    password: Test1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false


#https://www.journaldev.com/3481/hibernate-session-merge-vs-update-save-saveorupdate-persist-example